// Offline (single-player) boot: run the game server *in the page* and point the game client's WebSocket at it.
//
// The payload's index.html loads this module before /js/main.js (see patches/game-client.patch). When the launch
// mode is "solo" it imports the game's own server/net.js + server/lobby.js (flattened into the payload), starts a
// Network + Lobby over an in-memory loopback socket, and replaces globalThis.WebSocket so the game client talks to
// that in-page server instead of a remote one. In "multi" mode it does nothing and the real WebSocket is used.
//
// Launch mode, in order of precedence: `?mode=solo|multi` > `sp.shell.mode` (written by the shell picker) >
// `globalThis.__SP_OFFLINE__` (written by /js/runtime-config.js — true for a web build meant to run offline).
//
// The game repo is untouched: everything here is payload-side. The server modules run unmodified — only node:crypto
// / node:net are swapped for the shims through the payload's import map, and /server/data.js is a browser stand-in
// generated by tools/package-client.mjs.

import { Network, SessionRegistry } from '/server/net.js';
import { Lobby } from '/server/lobby.js';
import { loadData } from '/server/data.js';
import { createLoopbackPair } from '/offline/loopback.js';

/** server/index.js gets a real upgrade request; the in-page socket presents itself as loopback (never rate-limited). */
const LOCAL_REQ = { socket: { remoteAddress: '127.0.0.1' }, headers: {} };

const LOG = Object.freeze({
  info: (...a) => console.info('[offline]', ...a),
  warn: (...a) => console.warn('[offline]', ...a),
  error: (...a) => console.error('[offline]', ...a),
  debug() {},
});

/** Data files the simulation's content modules read through /data.js (public/js/battle/runner.js SIM_DATA_FILES). */
const SIM_DATA_FILES = Object.freeze(['chess', 'enemies', 'tokens', 'stages', 'waves', 'bonds', 'items', 'garrisons', 'bands', 'effects']);

/** @returns {'solo' | 'multi'} */
function launchMode() {
  try {
    const q = new URLSearchParams(globalThis.location?.search || '').get('mode');
    if (q === 'solo' || q === 'multi') return q;
  } catch { /* ignore */ }
  try {
    const stored = globalThis.localStorage?.getItem('sp.shell.mode');
    if (stored === 'solo' || stored === 'multi') return stored;
  } catch { /* ignore */ }
  return globalThis.__SP_OFFLINE__ ? 'solo' : 'multi';
}

if (launchMode() === 'solo') bootSolo();

function bootSolo() {
  const ready = startServer();
  globalThis.__SP_OFFLINE_READY__ = ready;
  restrictToSolo();
  // Replace the constructor synchronously so /js/main.js (loaded after this module) connects to the in-page server.
  // A constructor returning an object overrides `new`, so `new WebSocket(url)` yields the loopback client end.
  globalThis.WebSocket = function OfflineWebSocket() {
    const pair = createLoopbackPair();
    Promise.resolve(ready).then((srv) => {
      if (!srv) { pair.client._remoteClose(1011, 'offline server failed'); return; }
      srv.network.handleConnection(pair.server, LOCAL_REQ);
      pair.open();
    }).catch((e) => {
      console.error('[offline] in-page server failed to start', e);
      pair.client._remoteClose(1011, 'offline server failed');
    });
    return pair.client;
  };
}

/**
 * Offline is single-player only: the lobby screen is shared with the multiplayer build, so make solo the default
 * (`sp.pref.lobby.mode`, read by js/screens/lobby.js) and hide the 同盟模拟 card. Cosmetic + a preference, no game
 * source change; the multiplayer path (a different launch mode) leaves the card untouched.
 */
function restrictToSolo() {
  try { globalThis.localStorage?.setItem('sp.pref.lobby.mode', JSON.stringify('solo')); } catch { /* ignore */ }
  const style = document.createElement('style');
  style.textContent = '.mode-card--sp-solo-hidden{display:none !important}';
  document.documentElement.appendChild(style);
  const apply = () => {
    for (const el of document.querySelectorAll('.mode-card')) {
      if (/同盟模拟|ALLIANCE SIMULATION/.test(el.textContent || '')) el.classList.add('mode-card--sp-solo-hidden');
    }
  };
  apply();
  new MutationObserver(apply).observe(document.documentElement, { childList: true, subtree: true });
}

/** Build the in-page server (data first: the lobby / match engine read it synchronously through /server/data.js). */
async function startServer() {
  const data = await loadData();
  await preloadSimData(data);
  const registry = new SessionRegistry({});
  const lobby = new Lobby({ registry, log: LOG, getData: () => data });
  const network = new Network({ registry, handler: lobby, log: LOG });
  LOG.info(`single-player server ready (${Object.keys(data).length} data files)`);
  return { registry, lobby, network };
}

/**
 * Populate the /data.js shim (simdata.setSimData) so the simulation's content modules can read the game data. The
 * client normally fills it in when it starts a battle; doing it here decouples the in-page server from that timing
 * (both write the same data, so whichever runs last is harmless).
 */
async function preloadSimData(data) {
  try {
    const simdata = await import('/sim/simdata.js');
    const raw = {};
    for (const key of SIM_DATA_FILES) if (key in data) raw[key] = data[key];
    simdata.setSimData(raw);
    const support = await import('/sim/content/support/index.js');
    support.setGameData?.(null);
  } catch (e) {
    LOG.warn('simulation data preload failed', e);
  }
}
