// The in-page game server: the payload's own server modules (server/net.js + server/lobby.js + match/*) loaded and
// driven from a browser context. Two things use it — the offline single-player boot (/offline/bootstrap.js) and the
// phone-side LAN host (/offline/host-mobile.js, which bridges real sockets in over the Capacitor plugin) — so the
// transport is deliberately not decided here. Only node:crypto / node:net are swapped for the payload's shims by the
// import map, and /server/data.js is the browser stand-in generated by tools/package-client.mjs.

import { Network, SessionRegistry } from '/server/net.js';
import { Lobby } from '/server/lobby.js';
import { loadData } from '/server/data.js';

/** server/index.js hands its Network a real upgrade request; an in-page/bridged socket presents itself as loopback
 * (never rate-limited, and its "address" is only used for logging and the per-address cap). */
export const LOCAL_REQ = Object.freeze({ socket: { remoteAddress: '127.0.0.1' }, headers: {} });

/** A logger object with the console behind it — Network / Lobby call `log.info/warn/error`. */
export function makeLog(prefix) {
  return Object.freeze({
    info: (...a) => console.info(prefix, ...a),
    warn: (...a) => console.warn(prefix, ...a),
    error: (...a) => console.error(prefix, ...a),
    debug() {},
  });
}

/** Data files the simulation's content modules read through /data.js (public/js/battle/runner.js SIM_DATA_FILES). */
const SIM_DATA_FILES = Object.freeze(['chess', 'enemies', 'tokens', 'stages', 'waves', 'bonds', 'items', 'garrisons', 'bands', 'effects']);

/**
 * Build a ready-to-serve server: game data first (the lobby / match engine read it synchronously through
 * /server/data.js), then the registry, lobby and network the callers wire sockets into.
 * @param {{ log?: { info: Function, warn: Function, error: Function, debug?: Function } }} [opts]
 * @returns {Promise<{ registry: object, lobby: object, network: object, data: object }>}
 */
export async function startGameServer({ log = makeLog('[server]') } = {}) {
  const data = await loadData();
  await preloadSimData(data, log);
  const registry = new SessionRegistry({});
  const lobby = new Lobby({ registry, log, getData: () => data });
  const network = new Network({ registry, handler: lobby, log });
  return { registry, lobby, network, data };
}

/**
 * Populate the /data.js shim (simdata.setSimData) so the simulation's content modules can read the game data. The
 * client normally fills it in when it starts a battle; doing it here decouples the server from that timing (both
 * write the same data, so whichever runs last is harmless).
 */
async function preloadSimData(data, log) {
  try {
    const simdata = await import('/sim/simdata.js');
    const raw = {};
    for (const key of SIM_DATA_FILES) if (key in data) raw[key] = data[key];
    simdata.setSimData(raw);
    const support = await import('/sim/content/support/index.js');
    support.setGameData?.(null);
  } catch (e) {
    log.warn('simulation data preload failed', e);
  }
}
